// Feature-registry engine — loads every record's front matter plus
// roadmap.legacy.yaml, validates the whole registry, and renders the roadmap
// trees into docs/features/README.md between the roadmap markers.
// Record format and lifecycle: docs/features/README.md.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

export const ROOT = fileURLToPath(new URL("../..", import.meta.url));
export const FEATURES_DIR = join(ROOT, "docs", "features");
export const README = join(FEATURES_DIR, "README.md");
export const LEGACY = join(FEATURES_DIR, "roadmap.legacy.yaml");
const TEMPLATE = join(FEATURES_DIR, "TEMPLATE.md");

export const BEGIN_MARK =
  "<!-- roadmap:begin — generated by `npm run features:generate`; edit front matter or roadmap.legacy.yaml, then regenerate -->";
export const END_MARK = "<!-- roadmap:end -->";

const AREAS = ["frontend", "backend"];
const DELIVERY = [
  "backlog",
  "ready",
  "in-progress",
  "uat",
  "verified",
  "dropped",
];
const ROLLOUT = [
  "not-deployed",
  "local-only",
  "test-deployment",
  "dormant",
  "live",
];

// ---------------------------------------------------------------------------
// Minimal YAML-subset parser. Covers exactly what TEMPLATE.md's dialect uses:
// nested maps (2-space indent), sequences of scalars or maps, quoted strings,
// null, [] and inline arrays, comments. Anything else throws loudly — the
// registry must stay inside this dialect.
// ---------------------------------------------------------------------------

/** Parses the YAML subset used by feature front matter and the legacy file. */
export function parseYamlish(text) {
  const lines = [];
  for (const raw of text.split("\n")) {
    if (!raw.trim() || raw.trim().startsWith("#")) continue;
    lines.push(raw.replace(/\t/g, "  "));
  }
  let i = 0;
  const indentOf = (line) => line.match(/^ */)[0].length;

  function parseScalar(s) {
    s = s.trim();
    if (s.startsWith('"')) {
      const m = s.match(/^"((?:[^"\\]|\\.)*)"\s*$/);
      if (!m) throw new Error(`unterminated string: ${s}`);
      return m[1].replace(/\\(.)/g, "$1");
    }
    if (s.startsWith("'")) {
      const m = s.match(/^'([^']*)'\s*$/);
      if (!m) throw new Error(`unterminated string: ${s}`);
      return m[1];
    }
    s = s.replace(/\s+#.*$/, "").trim(); // trailing comment (unquoted values only)
    if (s === "null" || s === "~") return null;
    if (s === "[]") return [];
    if (s.startsWith("[") && s.endsWith("]"))
      return s
        .slice(1, -1)
        .split(",")
        .map((x) => parseScalar(x))
        .filter((x) => x !== "");
    if (s === "true") return true;
    if (s === "false") return false;
    if (/^-?\d+$/.test(s)) return Number(s);
    return s;
  }

  function parseSeq(indent) {
    const out = [];
    while (i < lines.length) {
      const line = lines[i];
      if (indentOf(line) !== indent || !line.trim().startsWith("- ")) break;
      const rest = line.trim().slice(2);
      if (/^[\w-]+:( |$)/.test(rest)) {
        lines[i] = " ".repeat(indent + 2) + rest; // treat "- key: v" as a map at indent+2
        out.push(parseMap(indent + 2));
      } else {
        out.push(parseScalar(rest));
        i++;
      }
    }
    return out;
  }

  function parseMap(indent) {
    const out = {};
    while (i < lines.length) {
      const line = lines[i];
      const ind = indentOf(line);
      if (ind < indent || line.trim().startsWith("- ")) break;
      if (ind > indent) throw new Error(`unexpected indent: "${line}"`);
      const m = line.trim().match(/^([\w][\w-]*):(?:[ \t]+(.*))?$/);
      if (!m) throw new Error(`cannot parse line: "${line}"`);
      i++;
      const [, key, rawVal] = m;
      if (
        rawVal === undefined ||
        rawVal.trim() === "" ||
        rawVal.trim().startsWith("#")
      ) {
        out[key] = parseBlock(indent + 2);
      } else {
        out[key] = parseScalar(rawVal);
      }
    }
    return out;
  }

  function parseBlock(indent) {
    const line = lines[i];
    if (line === undefined || indentOf(line) < indent) return null;
    return line.trim().startsWith("- ")
      ? parseSeq(indentOf(line))
      : parseMap(indentOf(line));
  }

  const value = parseBlock(0);
  if (i < lines.length) throw new Error(`trailing content: "${lines[i]}"`);
  return value;
}

/** Splits a record into { frontMatter, body }; throws when front matter is missing. */
export function parseRecord(text, file) {
  if (!text.startsWith("---\n"))
    throw new Error(`${file}: missing front matter`);
  const end = text.indexOf("\n---", 4);
  if (end === -1) throw new Error(`${file}: unterminated front matter`);
  return {
    frontMatter: parseYamlish(text.slice(4, end)),
    body: text.slice(end + 4),
  };
}

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------

const humanSchema = z.object({
  by: z.string(),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  environment: z.string(),
  evidence: z.string(),
});

const baseSchema = {
  schemaVersion: z.literal(1),
  id: z.string().regex(/^[a-z0-9]+(-[a-z0-9]+)*$/),
  parent: z.string(),
  area: z.enum(AREAS),
  order: z.number().int().nonnegative(),
  title: z.string().optional(),
  qualifier: z.string().optional(),
};

const featureSchema = z
  .object({
    ...baseSchema,
    kind: z.literal("feature"),
    delivery: z.enum(DELIVERY),
    rollout: z.enum(ROLLOUT),
    statusChangedAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    priority: z.enum(["p0", "p1", "p2"]).optional(),
    owner: z.string().optional(),
    target: z.string().optional(),
    dependsOn: z.array(z.string()).default([]),
    blockedBy: z.array(z.string()).default([]),
    verification: z.object({
      automated: z
        .array(z.string())
        .nullable()
        .transform((v) => v ?? []),
      human: humanSchema.nullable(),
    }),
    tracking: z.unknown().optional(),
  })
  .strict();

const groupSchema = z
  .object({ ...baseSchema, kind: z.literal("group") })
  .strict();

const legacySchema = z
  .object({
    id: baseSchema.id,
    title: z.string(),
    parent: z.string(),
    order: z.number().int().nonnegative(),
    delivery: z.enum(DELIVERY),
    rollout: z.enum(ROLLOUT).optional(), // optional only when delivery is dropped
    qualifier: z.string().optional(),
  })
  .strict();

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

function* recordFiles(dir = FEATURES_DIR) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name !== "generated") yield* recordFiles(path);
    } else if (
      entry.name.endsWith(".md") &&
      path !== TEMPLATE &&
      path !== README
    ) {
      yield path;
    }
  }
}

/** Loads and validates every record + legacy leaf. Throws with all problems listed. */
export function loadRegistry() {
  const nodes = [];
  const errors = [];

  for (const file of recordFiles()) {
    const rel = relative(ROOT, file);
    try {
      const { frontMatter, body } = parseRecord(
        readFileSync(file, "utf8"),
        rel,
      );
      const schema = frontMatter.kind === "group" ? groupSchema : featureSchema;
      const node = schema.parse(frontMatter);
      const h1 = body.match(/^# (.+)$/m)?.[1];
      node.label =
        node.kind === "group" ? (node.title ?? h1 ?? node.id) : basename(file);
      node.file = rel;
      if (node.kind === "group") {
        if (basename(file) !== "_group.md")
          errors.push(`${rel}: groups must be named _group.md`);
        if (basename(dirname(file)) !== node.id)
          errors.push(
            `${rel}: folder name must equal the group id "${node.id}"`,
          );
      } else if (basename(file) !== `${node.id}.md`) {
        errors.push(`${rel}: file name must equal the id "${node.id}"`);
      }
      nodes.push(node);
    } catch (e) {
      errors.push(
        `${rel}: ${e instanceof z.ZodError ? z.prettifyError(e) : e.message}`,
      );
    }
  }

  try {
    for (const leaf of parseYamlish(readFileSync(LEGACY, "utf8")) ?? []) {
      const node = legacySchema.parse(leaf);
      node.kind = "legacy";
      node.label = node.title;
      if (node.delivery !== "dropped" && !node.rollout)
        errors.push(
          `roadmap.legacy.yaml/${node.id}: rollout is required unless dropped`,
        );
      nodes.push(node);
    }
  } catch (e) {
    errors.push(
      `roadmap.legacy.yaml: ${e instanceof z.ZodError ? z.prettifyError(e) : e.message}`,
    );
  }

  const byId = new Map();
  for (const n of nodes) {
    if (byId.has(n.id))
      errors.push(
        `duplicate id "${n.id}" (${byId.get(n.id).file ?? "legacy"} + ${n.file ?? "legacy"})`,
      );
    byId.set(n.id, n);
  }
  for (const n of nodes) {
    const parent = byId.get(n.parent);
    if (!AREAS.includes(n.parent)) {
      if (!parent)
        errors.push(
          `${n.id}: parent "${n.parent}" is neither a group id nor an area`,
        );
      else if (parent.kind !== "group")
        errors.push(`${n.id}: parent "${n.parent}" is not a group`);
      else if (n.area && parent.area !== n.area)
        errors.push(
          `${n.id}: area "${n.area}" ≠ parent group's "${parent.area}"`,
        );
    }
    if (n.kind === "feature") {
      if (
        ["ready", "in-progress", "uat"].includes(n.delivery) &&
        !(n.priority && n.owner && n.target)
      )
        errors.push(
          `${n.id}: priority/owner/target are required while delivery is ready|in-progress|uat`,
        );
      if (n.delivery === "verified" && !n.verification.human)
        errors.push(
          `${n.id}: verification.human is required for delivery: verified`,
        );
      for (const ref of [...n.dependsOn, ...n.blockedBy])
        if (!byId.has(ref))
          errors.push(`${n.id}: unknown id "${ref}" in dependsOn/blockedBy`);
    }
  }

  if (errors.length)
    throw new Error(`registry invalid:\n  ✗ ${errors.join("\n  ✗ ")}`);
  return nodes;
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

const METER = {
  backlog: "○○○○ BACKLOG",
  ready: "●○○○ READY",
  "in-progress": "●●○○ IN PROGRESS",
  uat: "●●●○ UAT",
  verified: "●●●● VERIFIED",
  dropped: "✕ DROPPED",
};

// Rollout states that need no caveat at a given delivery stage; anything else
// is printed so the bare meter can't mislead (e.g. UAT but dormant).
const UNREMARKABLE = {
  backlog: ["not-deployed"],
  ready: ["not-deployed"],
  "in-progress": ["not-deployed", "local-only"],
  uat: ["test-deployment", "live"],
  verified: ["test-deployment", "live"],
  dropped: ROLLOUT,
};
const ROLLOUT_NOTE = {
  "not-deployed": "not deployed",
  "local-only": "local only",
  "test-deployment": "deployed (test)",
  dormant: "dormant",
  live: "live",
};

function statusText(n) {
  const notes = [];
  if (n.rollout && !UNREMARKABLE[n.delivery].includes(n.rollout))
    notes.push(ROLLOUT_NOTE[n.rollout]);
  if (n.qualifier) notes.push(n.qualifier);
  return `${METER[n.delivery]}${notes.length ? ` — ${notes.join("; ")}` : ""}`;
}

function wrap(text, firstPrefix, contPrefix, width = 80) {
  const words = text.split(" ");
  const out = [];
  let line = firstPrefix;
  let empty = true;
  for (const word of words) {
    if (!empty && line.length + 1 + word.length > width) {
      out.push(line);
      line = contPrefix;
      empty = true;
    }
    line += (empty ? "" : " ") + word;
    empty = false;
  }
  out.push(line);
  return out;
}

/** Renders the roadmap trees (both areas) from a validated registry. */
export function renderRoadmap(nodes) {
  const children = new Map();
  const childrenOf = (id) => children.get(id) ?? [];
  for (const n of nodes) {
    if (!children.has(n.parent)) children.set(n.parent, []);
    children.get(n.parent).push(n);
  }
  for (const list of children.values())
    list.sort((a, b) => a.order - b.order || a.label.localeCompare(b.label));

  const lines = [];
  function renderNode(n, branch, cont) {
    const text =
      n.kind === "group"
        ? `${n.label}${n.qualifier ? ` — ${n.qualifier}` : ""}`
        : `${n.label} ${statusText(n)}`;
    lines.push(...wrap(text, branch, cont + "    "));
    const kids = childrenOf(n.id);
    kids.forEach((kid, k) => {
      const last = k === kids.length - 1;
      renderNode(
        kid,
        cont + (last ? "└── " : "├── "),
        cont + (last ? "    " : "│   "),
      );
    });
  }

  const sections = {
    frontend: "### Frontend (storefront)",
    backend: "### Backend (admin + data)",
  };
  const out = [];
  for (const area of AREAS) {
    out.push(sections[area], "", "```text");
    const roots = childrenOf(area);
    roots.forEach((root, r) => {
      lines.length = 0;
      renderNode(root, "", "");
      out.push(...lines);
      if (r < roots.length - 1) out.push("");
    });
    out.push("```", "");
  }
  return out.join("\n").trimEnd();
}

/** Returns README text with the generated block replaced; throws when markers are missing. */
export function spliceReadme(readme, block) {
  const begin = readme.indexOf(BEGIN_MARK);
  const end = readme.indexOf(END_MARK);
  if (begin === -1 || end === -1 || end < begin)
    throw new Error("docs/features/README.md: roadmap markers not found");
  return (
    readme.slice(0, begin + BEGIN_MARK.length) +
    "\n\n" +
    block +
    "\n\n" +
    readme.slice(end)
  );
}

/** Regenerates the README roadmap block. Returns true when the file changed. */
export function generate({ write = true } = {}) {
  const readme = readFileSync(README, "utf8");
  const next = spliceReadme(readme, renderRoadmap(loadRegistry()));
  const changed = next !== readme;
  if (changed && write) writeFileSync(README, next);
  return changed;
}
